[Shaan] | Iot Device Catalogue Feature 1
ISD-Workshop-09-Group-02/IoTBay pull request #25
Opened 2023-04-27 10:28 UTC by ShaanCoding

2023-04-28 01:59 UTC, sebasptsch requested changes
There's a few things to address.

2023-04-28 01:59 UTC, sebasptsch commented on packages/backend/prisma/schema.prisma
> +  lastUpdated   DateTime         @default(now())
Use prisma `@updatedAt`

2023-04-28 01:59 UTC, sebasptsch commented on packages/backend/src/controllers/categories.controller.ts
> +export const deleteCategories = async (
Is there no schema for this request?

2023-04-28 01:59 UTC, sebasptsch commented on packages/backend/src/controllers/products.controller.ts
> +interface ICreateProduct {
this should be a schema

2023-04-28 01:59 UTC, sebasptsch commented on packages/backend/src/controllers/products.controller.ts
> +interface IDeleteProducts {
Should be a schema

2023-04-28 01:59 UTC, sebasptsch commented on packages/backend/src/controllers/products.controller.ts
> +      lastUpdated: new Date(),
Prisma has inbuilt updatedAt

2023-04-28 01:59 UTC, sebasptsch commented on packages/frontend/src/App.tsx
> +        loader: profileLoader(queryClient),
you can create a parent route that just uses the loader once. e.g. 
```tsx
{
  path: "/staff"
  loader: profileLoader(queryClient),
}
```
Child routes will get data from their nearest parent loader.

2023-04-28 01:59 UTC, sebasptsch commented on packages/frontend/src/features/IoTDeviceCatalogue/ProductTable.tsx
> +const ProductTable: React.FC<IProductTableProps> = ({
have a look at `@tanstack/table`. We can make a generic datatable to use across all components:
See example [here](https://github.com/Team3132/AttendanceSystem/blob/master/packages/frontend/src/components/DataTable.tsx)

2023-04-28 03:27 UTC, ShaanCoding commented on packages/backend/prisma/schema.prisma
> +  lastUpdated   DateTime         @default(now())
Done

2023-04-28 03:28 UTC, ShaanCoding commented on packages/backend/src/controllers/products.controller.ts
> +      lastUpdated: new Date(),
Done

2023-04-28 06:13 UTC, sebasptsch commented on packages/frontend/src/features/IoTDeviceCatalogue/ProductTable.tsx
> +const ProductTable: React.FC<IProductTableProps> = ({
defer

2023-04-29 05:03 UTC, sebasptsch approved these changes

2023-04-29 07:30 UTC, ShaanCoding commented
![image](https://user-images.githubusercontent.com/22236218/235289897-7284900b-ddb5-44d3-bccd-a99d114c7909.png)

2023-04-29 07:30 UTC, merged